version: "3.8"
services:
  frontend:
    image: halecakir/plantpal
    build: .
    ports:
      - 8502:8502
    volumes:
      - ./:/app/
    command : "streamlit run ui.py --server.port 8502 --server.fileWatcherType none"
    environment:
      - CHAT_ENDPOINT="http://backend:8000/predict"

  backend:
    image: halecakir/plantpal
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./:/app/
    command : "python api.py"
  
